language: python
virtualenv:
  system_site_packages: true
python:
  - "2.6"
  - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-netaddr python-setuptools
install: true
script: 
    - pwd
    - ls
    - python ./setup.py test

