language: python
python:
  - "2.6"
  - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-netaddr
install: true
script: 
    - pwd
    - ls
    - python ./setup.py test

